#pragma once
// Test-only certificates and keys (EC P-256, self-signed, valid for 100 years). Never use elsewhere.
//  good_*: CN=localhost, SAN DNS:localhost + IP:127.0.0.1
//  other_*: CN=other.example, SAN DNS:other.example only (host name mismatch when reached as 127.0.0.1)
namespace testcerts {
inline const char* good_cert = R"PEM(-----BEGIN CERTIFICATE-----
MIIBmzCCAUGgAwIBAgIURSQWAfEQzlPpbAKio/vtlc5MHyYwCgYIKoZIzj0EAwIw
FDESMBAGA1UEAwwJbG9jYWxob3N0MCAXDTI2MTAwOTE5MzA0NloYDzIxMjYwOTE1
MTkzMDQ2WjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAASxXWt9HqtwO1b6Ma24RCfstuXPUHjUcDbu9BaG32SuNnfdVPBu0he4
nZY9zEayzG8M6Ca5/ydOj1F1mYp4jVf0o28wbTAdBgNVHQ4EFgQUEXJKAvSQTCHB
R34GPpygeCOoqNcwHwYDVR0jBBgwFoAUEXJKAvSQTCHBR34GPpygeCOoqNcwDwYD
VR0TAQH/BAUwAwEB/zAaBgNVHREEEzARgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZI
zj0EAwIDSAAwRQIhAJMg+JLQ+ZrR+NwXPuTMSopP1UVU6tjw5mGc9dHTwgwTAiAR
2kFlpplppwDAzFu1cSVOFEn+LXatEkpfhNkITqjLIQ==
-----END CERTIFICATE-----
)PEM";
inline const char* good_key = R"PEM(-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgVD0W7QjUcq2zwE78
JDWkDm8LzWp95JVwgZSYgXOgNDyhRANCAASxXWt9HqtwO1b6Ma24RCfstuXPUHjU
cDbu9BaG32SuNnfdVPBu0he4nZY9zEayzG8M6Ca5/ydOj1F1mYp4jVf0
-----END PRIVATE KEY-----
)PEM";
inline const char* other_cert = R"PEM(-----BEGIN CERTIFICATE-----
MIIBoTCCAUegAwIBAgIUMK4pSt2BKvLFni09+4uCobu+7K8wCgYIKoZIzj0EAwIw
GDEWMBQGA1UEAwwNb3RoZXIuZXhhbXBsZTAgFw0yNjEwMDkxOTMwNDZaGA8yMTI2
MDkxNTE5MzA0NlowGDEWMBQGA1UEAwwNb3RoZXIuZXhhbXBsZTBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABELAeJpaFhNglnPO5aQ7IHjb+ZPKUpzazr1Mry2yYe/T
Ds6CpxvlTlHMkRwQNP8U/5PLCa8gZPdfyUVLKJ2nY5+jbTBrMB0GA1UdDgQWBBRy
pjAOxrb6Ea+XJzj1jEjIHoQSVzAfBgNVHSMEGDAWgBRypjAOxrb6Ea+XJzj1jEjI
HoQSVzAPBgNVHRMBAf8EBTADAQH/MBgGA1UdEQQRMA+CDW90aGVyLmV4YW1wbGUw
CgYIKoZIzj0EAwIDSAAwRQIgCDRNpcGIJBM+BXObpX0UyTdoBY6xUbLkKbUvnxeG
N7MCIQCAYc6FXq4aEcQNg81bdfFl7x5EDrgEF9SxTwIZ4q3AIA==
-----END CERTIFICATE-----
)PEM";
inline const char* other_key = R"PEM(-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg7t88zNXUdPkbnc5H
FttC0kyCqizvK5sEdZJHPKQ0nYmhRANCAARCwHiaWhYTYJZzzuWkOyB42/mTylKc
2s69TK8tsmHv0w7Ogqcb5U5RzJEcEDT/FP+TywmvIGT3X8lFSyidp2Of
-----END PRIVATE KEY-----
)PEM";
} // namespace testcerts
